# playbook.yml
- hosts: rts
  gather_facts: false
  tasks:
  - name: include apt tasks
    include_role:
      name: ensure_python
      # FIXME: Should this be decided from a preconfigured OS type?
      tasks_from: netbsd.yaml


#  tasks:
#    - command: which python
#      register: result
#    - debug:
#        var: result.stdout
#    - debug:
#        msg: |-
#          {% for i in _vars %}
#          {{ i }}:
#            {{ lookup('vars', i)|to_nice_yaml|indent(2) }}
#          {% endfor %}
#      vars:
#        _vars: "{{ query('varnames', '.*python.*') }}"