# Example inventory file for an embedded HA-STS installation

# NOTE: Some of these nodes are running on NetBSD (https://docs.ansible.com/ansible/latest/os_guide/intro_bsd.html)

# Real-Time Services
[rts]
rts1 ansible_connection=paramiko

# Command aNd Control
[cnc]
cnc1 ansible_connection=paramiko

# Time Series Management
[tsm]
tsm1
