# Example inventory file for an embedded HA-STS installation

# NOTE: Some of these nodes are running on NetBSD
#       https://docs.ansible.com/ansible/latest/os_guide/intro_bsd.html
[all:vars]
certificates_directory="./certificates"
ca_certificate_organization: "Organization"
ca_certificate_email: "baduser@example.com"
ca_certificate_common_name: "certificate.example.com"


# Real-Time Services
# Currently using NetBSD on RPi4
[rts]
rts1 ansible_host=example.com ansible_user=user ansible_become_method=su ansible_become_user=root ansible_become_password=password ansible_python_interpreter=/usr/pkg/bin/python3.13

# Command aNd Control
# Currently using NetBSD on RPi4
[cnc]
cnc1 ansible_host=example.com ansible_user=user ansible_become_method=su ansible_become_user=root ansible_become_password=password ansible_python_interpreter=/usr/pkg/bin/python3.13

# Time Series Management
# Currently using Raspberry Pi OS (legacy, based on Debian Bookworm) on RPi5
[tsm]
tsm1 ansible_host=example.com ansible_user=user ansible_become_method=su ansible_become_user=root ansible_become_password=password ansible_python_interpreter=/usr/pkg/bin/python3.13
