---
- hosts: rts
  roles:
    - role: common
    - role: mosquitto
    - role: name_com_dyndns
      vars:
        name_com_dyndns_username: "{{ hostvars[inventory_hostname].name_com_dyndns_username }}"
        name_com_dyndns_token: "{{ hostvars[inventory_hostname].name_com_dyndns_token }}"
        name_com_dyndns_domain: "{{ hostvars[inventory_hostname].name_com_dyndns_domain }}"
        name_com_dyndns_hostname: "{{ hostvars[inventory_hostname].name_com_dyndns_hostname }}"
