---
- hosts: 127.0.0.1
  connection: local
  roles:
    - role: local_ca
      vars:
        certificate_directory: "{{ hostvars[inventory_hostname].certificates_directory }}"
        certificate_organization: "{{ hostvars[inventory_hostname].ca_certificate_organization }}"
        certificate_email: "{{ hostvars[inventory_hostname].ca_certificate_email }}"
        certificate_common_name: "{{ hostvars[inventory_hostname].ca_certificate_common_name }}"

- hosts: rts
  roles:
    - role: common
    - role: mosquitto
    - role: name_com_dyndns
      vars:
        name_com_dyndns_username: "{{ hostvars[inventory_hostname].name_com_dyndns_username }}"
        name_com_dyndns_token: "{{ hostvars[inventory_hostname].name_com_dyndns_token }}"
        name_com_dyndns_domain: "{{ hostvars[inventory_hostname].name_com_dyndns_domain }}"
        name_com_dyndns_hostname: "{{ hostvars[inventory_hostname].name_com_dyndns_hostname }}"
