---
- name: Install the Supervisord package
  ansible.builtin.package:
    name: py313-supervisor
    state: present
  become: true

- name: Configure the Supevisord package
  ansible.builtin.template:
    src: templates/supervisord.conf.j2
    dest: /usr/pkg/etc/supervisord.conf
  become: true

- name: Create the configuration directory
  ansible.builtin.file:
    path: /usr/pkg/etc/supervisord.conf.d
    state: directory
    mode: '0755'
  become: true

- name: Copy startup script
  ansible.builtin.copy:
    src: /usr/pkg/share/examples/rc.d/supervisord
    dest: /etc/rc.d/supervisord
    remote_src: true
    mode: '0555'
  become: true

- name: Ensure Supervisord is enabled on startup
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    regexp: '^supervisord='
    line: supervisord=YES
  become: true
